import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {accountResponse} from './account.mjs';
import {localDatabase} from './local-d1.mjs';
import {hashPassword} from 'better-auth/crypto';
import {notebookCipher,ENCRYPTED_PREFIX} from './notebook-crypto.mjs';
const origin='https://jibro.example.test',password='Local-test-passphrase-93';
function setup(){const env={DB:localDatabase(),JIBRO_APP_ORIGIN:origin,JIBRO_AUTH_SECRET:randomBytes(48).toString('base64url'),JIBRO_NOTEBOOK_KEYS:JSON.stringify({active:'test',keys:{test:randomBytes(32).toString('base64url')}})};let ip=0;return {env,client(){const cookies=new Map(),address='192.0.2.'+(++ip);return {cookies,async request(path,method='GET',data,extra={}){const response=await accountResponse(new Request(origin+path,{method,headers:{Origin:origin,'CF-Connecting-IP':address,'X-Jibro-Request':'1','Content-Type':'application/json',Cookie:[...cookies].map(([k,v])=>k+'='+v).join('; '),...extra},...(data?{body:JSON.stringify(data)}:{})}),env);for(const c of response.headers.getSetCookie()){const [kv]=c.split(';'),[key,...v]=kv.split('=');if(v.join('='))cookies.set(key,v.join('='));else cookies.delete(key);}return {status:response.status,data:await response.json(),headers:response.headers};}};}};}
const registration=email=>({email,password,nickname:'테스트',terms:true,privacy:true,age:true,policyVersion:'2026-09-26'});
const notebook={name:'테스트',region:'서울',saved:['lh-one'],activeNoticeId:'lh-one',noticeData:{'lh-one':{done:['doc'],conditions:['age']}},noticeSnapshots:{'lh-one':{url:'https://apply.lh.or.kr/',title:'테스트 공고'}}};
test('blank signup nicknames get a six-digit temporary name; a displayed draft name survives login',async()=>{const t=setup(),a=t.client(),b=t.client();try{
 const automatic=await a.request('/api/account/register','POST',{...registration('auto-name@example.test'),nickname:'   '});assert.equal(automatic.status,200);assert.match(automatic.data.user.nickname,/^임시\d{6}$/);
 const draft=await b.request('/api/account/register','POST',{...registration('draft-name@example.test'),nickname:'임시123456'});assert.equal(draft.status,200);assert.equal(draft.data.user.nickname,'임시123456');
 await b.request('/api/account/logout','POST',{});const restored=await b.request('/api/account/login','POST',{email:'draft-name@example.test',password});assert.equal(restored.data.user.nickname,'임시123456');
}finally{t.env.DB.sqlite.close();}});
test('signup profile belongs only to its member, persists through login and can be withdrawn without losing notice records',async()=>{const t=setup(),a=t.client(),b=t.client();try{
 const profile={consent:true,consentVersion:'2026-09-26',birthDate:'1999-10-01',householdSize:3,selfHome:'no',monthlyIncome:3000000,incomeScope:'household'};
 assert.equal((await a.request('/api/account/register','POST',{...registration('invalid-profile@example.test'),applicantProfile:{...profile,consent:false}})).status,400);
 assert.equal(t.env.DB.sqlite.prepare('SELECT count(*) n FROM auth_user').get().n,0);
 assert.equal((await a.request('/api/account/register','POST',{...registration('personal@example.test'),applicantProfile:profile})).status,200);
 const raw=t.env.DB.sqlite.prepare('SELECT payload FROM jibro_member_notebooks').get().payload;assert.ok(raw.startsWith(ENCRYPTED_PREFIX));assert.ok(!raw.includes(profile.birthDate));assert.ok(!raw.includes('monthlyIncome'));
 let saved=(await a.request('/api/member-notebook')).data;assert.equal(saved.revision,1);assert.equal(saved.state.applicantProfile.householdSize,3);
 await b.request('/api/account/register','POST',registration('other-personal@example.test'));assert.equal((await b.request('/api/member-notebook')).data.state,null);
 await a.request('/api/account/logout','POST',{});await a.request('/api/account/login','POST',{email:'personal@example.test',password});
 saved=(await a.request('/api/member-notebook')).data;assert.equal(saved.state.applicantProfile.monthlyIncome,3000000);
 assert.equal((await a.request('/api/member-notebook','PUT',{state:{...notebook,applicantProfile:saved.state.applicantProfile},revision:saved.revision})).status,200);
 saved=(await a.request('/api/member-notebook')).data;
 assert.equal((await a.request('/api/member-notebook','PUT',{state:{...saved.state,applicantProfile:null},revision:saved.revision})).status,200);
 saved=(await a.request('/api/member-notebook')).data;assert.equal(saved.state.applicantProfile,null);assert.deepEqual(saved.state.noticeData['lh-one'].conditions,['age']);
 assert.equal((await b.request('/api/member-notebook')).data.state,null);
}finally{t.env.DB.sqlite.close();}});
test('encryption failures never fall back to plaintext or overwrite records; legacy member records migrate safely',async()=>{const t=setup(),a=t.client(),b=t.client();try{
 const user=(await a.request('/api/account/register','POST',registration('encryption@example.test'))).data.user;
 const other=(await b.request('/api/account/register','POST',registration('encrypted-other@example.test'))).data.user;
 t.env.DB.sqlite.prepare('INSERT INTO jibro_member_notebooks VALUES (?,?,?,?)').run(user.id,JSON.stringify(notebook),7,'legacy-time');
 assert.equal((await a.request('/api/account')).status,200);
 const migrated=t.env.DB.sqlite.prepare('SELECT * FROM jibro_member_notebooks WHERE user_id=?').get(user.id);assert.ok(migrated.payload.startsWith(ENCRYPTED_PREFIX));assert.equal(migrated.revision,7);assert.equal(migrated.updated_at,'legacy-time');
 assert.deepEqual((await a.request('/api/member-notebook')).data.state,notebook);
 t.env.DB.sqlite.prepare('INSERT INTO jibro_member_notebooks VALUES (?,?,?,?)').run(other.id,migrated.payload,1,'tamper-test');
 assert.equal((await b.request('/api/member-notebook')).status,503);
 const key=t.env.JIBRO_NOTEBOOK_KEYS;delete t.env.JIBRO_NOTEBOOK_KEYS;
 assert.equal((await a.request('/api/member-notebook')).status,503);
 assert.equal((await a.request('/api/member-notebook','PUT',{state:notebook,revision:7})).status,503);
 const count=t.env.DB.sqlite.prepare('SELECT count(*) n FROM auth_user').get().n;
 assert.equal((await t.client().request('/api/account/register','POST',{...registration('missing-key@example.test'),applicantProfile:{consent:true,consentVersion:'2026-09-26',householdSize:2}})).status,503);
 assert.equal(t.env.DB.sqlite.prepare('SELECT count(*) n FROM auth_user').get().n,count);
 assert.equal(t.env.DB.sqlite.prepare('SELECT payload FROM jibro_member_notebooks WHERE user_id=?').get(user.id).payload,migrated.payload);
 t.env.JIBRO_NOTEBOOK_KEYS=key;
 assert.equal((await a.request('/api/member-notebook','PUT',{state:{...notebook,region:'경기도'},revision:7})).status,200);
 const stored=t.env.DB.sqlite.prepare('SELECT payload FROM jibro_member_notebooks WHERE user_id=?').get(user.id).payload;
 assert.equal((await notebookCipher(t.env).open(user.id,stored)).state.region,'경기도');
}finally{t.env.DB.sqlite.close();}});
test('a failed initial profile write reports retry after successful signup, never fabricates saved profile',async()=>{const t=setup(),a=t.client(),prepare=t.env.DB.prepare;try{
 t.env.DB.prepare=sql=>{if(sql.startsWith('INSERT INTO jibro_member_notebooks'))throw Error('simulated storage failure');return prepare(sql);};
 const r=await a.request('/api/account/register','POST',{...registration('retry-profile@example.test'),applicantProfile:{consent:true,consentVersion:'2026-09-26',householdSize:2}});
 assert.equal(r.status,200);assert.equal(r.data.profileSaved,false);assert.ok(r.data.user);assert.equal((await a.request('/api/account')).data.user.email,'retry-profile@example.test');
 t.env.DB.prepare=prepare;assert.equal((await a.request('/api/member-notebook')).data.state,null);
}finally{t.env.DB.sqlite.close();}});
test('email signup, hashed credentials, session cookies, logout, wrong password and re-login',async()=>{const t=setup(),a=t.client();try{
 assert.equal((await a.request('/api/account/register','POST',{...registration('one@example.test'),terms:false})).status,400);
 assert.equal((await a.request('/api/account/register','POST',{...registration('one@example.test'),password:'short'})).status,400);
 const signup=await a.request('/api/account/register','POST',registration('ONE@example.test'));assert.equal(signup.status,200,JSON.stringify(signup.data));assert.equal(signup.data.user.email,'one@example.test');
 assert.match(signup.headers.get('set-cookie'),/HttpOnly/i);assert.match(signup.headers.get('set-cookie'),/Secure/i);assert.match(signup.headers.get('set-cookie'),/SameSite=Lax/i);assert.equal(signup.data.token,undefined);
 const stored=t.env.DB.sqlite.prepare('SELECT password FROM auth_account').get().password;assert.notEqual(stored,password);assert.ok(stored.length>100);
 assert.equal((await a.request('/api/account')).data.user.email,'one@example.test');
 const duplicate=t.client();assert.equal((await duplicate.request('/api/account/register','POST',registration('one@example.test'))).status,422);
 const stolenCookie=[...a.cookies].map(([k,v])=>k+'='+v).join('; ');
 assert.equal((await a.request('/api/account/logout','POST',{})).status,200);assert.equal((await a.request('/api/member-notebook')).status,401);
 assert.equal((await duplicate.request('/api/member-notebook','GET',null,{Cookie:stolenCookie})).status,401);
 assert.equal((await a.request('/api/account/login','POST',{email:'one@example.test',password:'wrong'})).status,401);
 assert.equal((await a.request('/api/account/login','POST',{email:'ONE@example.test',password})).status,200);
}finally{t.env.DB.sqlite.close();}});
test('member ownership, CSRF, revisions, direct signup bypass, password change and account deletion',async()=>{const t=setup(),a=t.client(),b=t.client(),guest=t.client();try{
 assert.equal((await guest.request('/api/auth/sign-up/email','POST',registration('bypass@example.test'))).status,404);
 assert.equal((await guest.request('/api/account/register','POST',registration('csrf@example.test'),{Origin:'https://evil.test'})).status,403);
 await a.request('/api/account/register','POST',registration('a@example.test'));await b.request('/api/account/register','POST',registration('b@example.test'));
 assert.equal((await a.request('/api/member-notebook','PUT',{state:notebook,revision:0})).status,200);
 assert.equal((await a.request('/api/member-notebook','PUT',{state:notebook,revision:0})).status,409);
 assert.equal((await b.request('/api/member-notebook','GET',null,{'X-Jibro-Device':'a','oai-authenticated-user-id':'a'})).data.state,null);
 assert.equal((await guest.request('/api/member-notebook','GET',null,{'oai-authenticated-user-id':'a'})).status,401);
 assert.deepEqual((await a.request('/api/member-notebook')).data.state.noticeData['lh-one'].done,['doc']);
 assert.equal((await a.request('/api/account','DELETE',{confirm:'회원 탈퇴',password:'wrong'})).status,400);
 assert.equal((await a.request('/api/account/password','POST',{currentPassword:password,newPassword:password+'new'})).status,200);
 assert.equal((await a.request('/api/account','DELETE',{confirm:'회원 탈퇴',password:password+'new'})).status,200);
 assert.equal((await a.request('/api/member-notebook')).status,401);assert.equal(t.env.DB.sqlite.prepare('SELECT count(*) n FROM jibro_member_notebooks').get().n,0);
 assert.equal((await b.request('/api/account')).data.user.email,'b@example.test');
}finally{t.env.DB.sqlite.close();}});
test('rate limits persist in the database',async()=>{const t=setup(),a=t.client();try{let response;for(let i=0;i<9;i++)response=await a.request('/api/account/login','POST',{email:'missing@example.test',password});assert.equal(response.status,429);assert.ok(t.env.DB.sqlite.prepare('SELECT count(*) n FROM auth_rate_limit').get().n>0);}finally{t.env.DB.sqlite.close();}});
test('password changes revoke other sessions; expired sessions cannot read records',async()=>{const t=setup(),a=t.client(),other=t.client();try{
 await a.request('/api/account/register','POST',registration('sessions@example.test'));await other.request('/api/account/login','POST',{email:'sessions@example.test',password});
 assert.equal((await a.request('/api/account/password','POST',{currentPassword:password,newPassword:password+'new'})).status,200);
 assert.equal((await other.request('/api/member-notebook')).status,401);
 t.env.DB.sqlite.prepare('UPDATE auth_session SET expires_at = ?').run(Date.now()-1000);assert.equal((await a.request('/api/member-notebook')).status,401);
}finally{t.env.DB.sqlite.close();}});
test('missing storage and malformed write requests return clear errors without exposing details',async()=>{const t=setup(),a=t.client();try{
 assert.equal((await a.request('/api/account/register','POST',registration('format@example.test'),{'Content-Type':'text/plain'})).status,415);
 const response=await accountResponse(new Request(origin+'/api/account'),{});assert.equal(response.status,503);const data=await response.json();assert.equal(data.error,'unavailable');assert.ok(!data.message.includes('SECRET'));
}finally{t.env.DB.sqlite.close();}});
test('private Site test account needs explicit scope and survives missing or site-specific platform identity',async()=>{const t=setup(),owner=t.client(),guest=t.client();try{
 const credentials={email:'admin',password:'admin'};
 assert.equal((await owner.request('/api/account/login','POST',credentials)).status,401);
 t.env.JIBRO_TEST_LOGIN_ENABLED='1';t.env.JIBRO_TEST_PASSWORD_HASH=await hashPassword('admin');
 assert.equal((await owner.request('/api/account/login','POST',credentials,{'oai-authenticated-user-id':'owner'})).status,401);
 t.env.JIBRO_TEST_LOGIN_SCOPE='public';assert.equal((await owner.request('/api/account')).data.testLoginAvailable,false);
 t.env.JIBRO_TEST_LOGIN_SCOPE='owner-private-site';
 assert.equal((await owner.request('/api/account')).data.testLoginAvailable,true);
 t.env.JIBRO_APP_ORIGIN='https://another.example.test';assert.equal((await owner.request('/api/account')).data.testLoginAvailable,false);t.env.JIBRO_APP_ORIGIN=origin;
 assert.equal((await guest.request('/api/account/register','POST',registration('admin@jibro.test'))).status,400);
 assert.equal((await owner.request('/api/account/login','POST',{...credentials,password:'wrong'})).status,401);
 assert.equal(t.env.DB.sqlite.prepare('SELECT count(*) n FROM auth_user').get().n,0);
 assert.equal((await owner.request('/api/account/login','POST',credentials)).status,200);
 assert.equal((await owner.request('/api/account')).data.user.nickname,'관리자 (테스트)');
 assert.equal((await owner.request('/api/account','GET',null,{'oai-authenticated-user-id':'site-scoped-owner-id'})).data.user.nickname,'관리자 (테스트)');
 assert.equal((await owner.request('/api/member-notebook','PUT',{state:notebook,revision:0})).status,200);
 assert.equal((await guest.request('/api/member-notebook')).status,401);
 assert.equal((await owner.request('/api/account/password','POST',{currentPassword:'admin',newPassword:password})).status,200);
 assert.equal((await owner.request('/api/account/login','POST',credentials)).status,401);
 assert.equal((await owner.request('/api/account/login','POST',{email:'admin',password})).status,200);
 assert.deepEqual((await owner.request('/api/member-notebook')).data.state.saved,['lh-one']);
 delete t.env.JIBRO_TEST_LOGIN_SCOPE;assert.equal((await owner.request('/api/member-notebook')).status,401);
 t.env.JIBRO_TEST_LOGIN_SCOPE='owner-private-site';t.env.JIBRO_TEST_LOGIN_ENABLED='0';assert.equal((await owner.request('/api/member-notebook')).status,401);
}finally{t.env.DB.sqlite.close();}});
